### ISSUE TITLE
Problem: .vscode dir is tracked in git

### ISSUE THREAD

**Issue by ablwr** [artefactual-labs/enduro#11]
I don't think your .vscode directory needs to be checked into the repo

**Comment by sevein** [comment]
The compelling part of tracking .vscode is that we can suggest an opinionated development environment, if you happen to use vscode. We could go further and set defaults for launch and task settings too. Many repos seem to be doing this, e.g. https://github.com/search?utf8=%E2%9C%93&q=.vscode&ref=simplesearch.

[TypeScript](https://github.com/microsoft/TypeScript/tree/master/.vscode) tracks templates. That's perhaps a better way if you didn't want to enforce your defaults, but they're also a large community!

Perhaps we could update our .gitignore like the following: https://github.com/github/gitignore/blob/master/Global/VisualStudioCode.gitignore. That would allow users to set up vscode workspaces with custom settings in various places within the repo tree.

**Comment by sevein** [comment]
I think for now I'll keep the .vscode around but I'd be happy to continue the conversation.
