### ISSUE TITLE
Problem: ${PWD} variable in docker-compose does not look like it will work

### ISSUE THREAD

**Issue by ross-spencer** [artefactual-labs/enduro#117]
When running `docker compose up -d` I get `WARNING: The PWD variable is not set. Defaulting to a blank string.` I had been trying to figure out what that was previously, but when I realized I couldn't wipe my configuration I discovered it was because I was finding it on `/hack/..` on root. As I run `docker` as sudo then that makes this possible to do that. (Perhaps it's possible without explicitly calling `sudo`?). 

There's a little more elaboration here: https://stackoverflow.com/questions/41948232/docker-compose-wont-find-pwd-environment-variable

Running with `./hack/` as in other lines seems to work well. It looks like just two instances to replace if it is a suitable fix to just replace `${PWD}` with that:

* [L13](  https://github.com/artefactual-labs/enduro/blob/a23c5e4e7b28720a600f64721fd0cf623abca18b/docker-compose.yml#L13)
* [L53](https://github.com/artefactual-labs/enduro/blob/a23c5e4e7b28720a600f64721fd0cf623abca18b/docker-compose.yml#L53)

**Comment by sevein** [comment]
Thank you, you're totally right. Fixed in 3bf3ac7. I'd avoid sudo if you can too, it's usually enough if you add your user to the docker group.

**Comment by ross-spencer** [comment]
I'll give that a try @sevein that would help somewhat.

**Comment by sevein** [comment]
Fixed in https://github.com/artefactual-labs/enduro/commit/3bf3ac78da47d4eda0e9341d00450789645d3e8a.
