### ISSUE TITLE
Problem: We might be missing a few logical steps in the developer docs

### ISSUE THREAD

**Issue by ross-spencer** [artefactual-labs/enduro#118]
Successfully managed to setup Enduro using `docker-compose` with `minio` and I think too file-system watching. 

Having run through the docs I feel the following might be missing (or at least might be pointed to from the developer environment pages):

1. Database setup.

I followed the docs by the letter [here](https://enduroproject.netlify.app/docs/development/environment/) but the `cadence-seed` task fails because the database needs to be setup and permissions granted to the `enduro` user, so I followed those instructions [here](https://enduroproject.netlify.app/docs/installation/#database-setup) from the general docs setup. This then allowed me to continue to the end of the deployment.

```
docker-compose run --rm cadence /seed.sh
+ SCHEMA_DIR=/etc/cadence/schema/mysql/v57/cadence/versioned
+ VISIBILITY_SCHEMA_DIR=/etc/cadence/schema/mysql/v57/visibility/versioned
+ DBNAME=cadence
+ VISIBILITY_DBNAME=cadence_visibility
+ MYSQL_ADDR=mysql
+ MYSQL_USER=root
+ MYSQL_PWD=root123
+ cadence-sql-tool --ep mysql -u root --pw root123 --db cadence setup-schema -v 0.0
2020/05/21 17:22:15 Error 1049: Unknown database 'cadence'
Makefile:99: recipe for target 'cadence-seed' failed
```

**NB.** First time running `docker-compose up -d` I also see the services haven't all started as anticipated, with:
```
ross-spencer@artefactual:~/git/artefactual-labs/enduro$ sudo docker-compose ps
WARNING: The PWD variable is not set. Defaulting to a blank string.
        Name                      Command                 State               Ports          
---------------------------------------------------------------------------------------------
enduro_cadence-web_1   docker-entrypoint.sh node  ...   Up           127.0.0.1:7440->8088/tcp
enduro_cadence_1       /docker-entrypoint.sh cade ...   Restarting                           
enduro_minio_1         /usr/bin/docker-entrypoint ...   Exit 1                               
enduro_mysql_1         docker-entrypoint.sh --cha ...   Exit 1                               
enduro_redis_1         docker-entrypoint.sh redis ...   Up           127.0.0.1:7470->6379/tcp
```
And:
```
mysql_1        | 2020-05-21 17:17:03+00:00 [Note] [Entrypoint]: Temporary server started.
mysql_1        | Warning: Unable to load '/usr/share/zoneinfo/iso3166.tab' as time zone. Skipping it.
mysql_1        | Warning: Unable to load '/usr/share/zoneinfo/leap-seconds.list' as time zone. Skipping it.
mysql_1        | Warning: Unable to load '/usr/share/zoneinfo/zone.tab' as time zone. Skipping it.
mysql_1        | Warning: Unable to load '/usr/share/zoneinfo/zone1970.tab' as time zone. Skipping it.
mysql_1        | 2020-05-21 17:17:05+00:00 [Note] [Entrypoint]: Creating user enduro
mysql_1        | 
mysql_1        | 2020-05-21 17:17:05+00:00 [Note] [Entrypoint]: /usr/local/bin/docker-entrypoint.sh: running /docker-entrypoint-initdb.d/docker-init.sql
mysql_1        | ERROR: Can't initialize batch_readline - may be the input source is a directory or a block device.
```
So I don't know if there is anything to note about that in the docs yet. Other than it doesn't hurt to try `docker-compose restart <service-name>` which got everything up and running, and ocassionally retry a step, e.g. registering the domain step later on took two attempts which I didn't debug why.

2. Minio configuration: Docker Compose

It looks like we may need to include the environment values for our access id and keys in docker-compose. I also added the bucket region just in case:
```
      - "MINIO_REGION_NAME=us-west-1"
      - "MINIO_ACCESS_KEY=<ACCESS_KEY>"
      - "MINIO_SECRET_KEY=<SECRET_KEY>"
```

3. Minio configuration: Docker Compose

This is a good reference doc for folks: https://docs.min.io/docs/minio-bucket-notification-guide.html#Redis I think perhaps if we can expand our setup notes at all we could provide some manual checks. In my case, My messages weren't being sent to redis, so some useful commands were:

* Checking what was configured for enduro redis: `mc admin config get enduro/ notify_redis` 
* Checking the events that were configured: `./mc event list enduro/sips` 
* Manually setting the conifg for notifications and the fields that are needed, I believe: `mc admin config set enduro/ notify_redis enable="on" address="redis:6379" format="access" key="minio-events" password="" queue_dir="/tmp/events" queue_limit="1000"` and also, `mc event add enduro/sips arn:minio:sqs:us-west-1:1:redis` where the `SQS ARN` can be recovered from the `minio` logs on startup, e.g. `docker-compose logs -f minio`. 

The config checks were useful as I think I was experiencing a problem as a by-product of: https://github.com/artefactual-labs/enduro/issues/117

It's also useful to know that setting up the notifications is pretty easy to do manually. (Debugging wasn't so hard though and introduced me to the different components :wink: )

4. Golang/docker-compose differences

This is more about my config, and I have to understand if I want to give docker root access. But with some of the commands i run using `sudo` to let `docker-compose` work, everything works okay. But with some commands, e.g. `make migrations ui` what i want to do is use Golang in my user space, and `docker-compose` as `sudo`. These two things are incompatible. I don't think any commands do both though, it's a workflow thing where i need to know, `make x` as `sudo`. `make y` as `$(whoami)`.

**Conclusion**

A couple of thoughts that might be useful to others and we might follow up in the docs on. 

Docs referenced: https://enduroproject.netlify.app/docs/development/environment/

**Comment by sevein** [comment]
I've updated the access and secret keys here https://github.com/artefactual-labs/enduro/commit/045cc6d78f9341d0a15d4e79bf9d9ffde9a4cf18.

You may have noticed in 045cc6d78 that we track our MinIO's dev config in git so I'm hoping that the command that you are suggesting isn't really needed, unless https://github.com/artefactual-labs/enduro/issues/117 is causing the issue like I think you're suggesting. I think that your problems with the database also relate to #117.

I've pushed some changes to [`website/content/en/docs/development/environment.md`](https://enduroproject.netlify.app/docs/development/environment/) and started over with `docker-compose down --volumes`. It seemed to work for me this time.

**Comment by sevein** [comment]
The issue with sudo is now mentioned in the docs, see https://enduroproject.netlify.app/docs/development/environment/. Feel free to continue using this issue to share your discoveries.
