### ISSUE TITLE
Problem: ability to validate presence of checksum file not present

### ISSUE THREAD

**Issue by evelynPM** [artefactual-labs/enduro#120]
Archivematica can verify checksums for files in a transfer if the transfer includes a checksum file in a metadata directory in the top-level folder. However, it lacks the ability to require that such a file be present. 

The proposed solution is to have Enduro check that a metadata/checksum.xxx (for example, checksum.md5) file exists and to provide an error notification if it is absent. This would be a configurable option.

**Comment by replaceafill** [comment]
@evelynPM @scollazo This has been addressed in release [`v0.29.0`](https://github.com/artefactual-labs/enduro/releases/tag/v0.29.0). There's a [new `validation` section](https://github.com/artefactual-labs/enduro/blob/4bd470a04eb1b8f2e06e541b7f52d24c86019ea3/enduro.toml#L52-L53) in the configuration file to enable it:

```toml
[validation]
checksumsCheckEnabled = false
```
