### ISSUE TITLE
Problem: enduro slots don't get released for some types of failures

### ISSUE THREAD

**Issue by scollazo** [artefactual-labs/enduro#272]
Under some circunstances, enduro slots get used by a failed transfer, and never released.

**Comment by scollazo** [comment]
I have not been able to reproduce this in a reliable way, but I'm doing the following:

- Start some transfers in enduro. There will be as many "In progress" transfers as capacity says
- Restart archivematica-mcp-server, you might need to do it more than once, as it doesn't always work the first try.

After that, Enduro shows some transfers as "In progress", but they might have failed, or be stuck in Archivematica. If you try to cancel the job, it goes into "Error", but no transfers in "Queue" state go into "In progress", so the transfer slot is unused.

**Comment by scollazo** [comment]
Also, after restarting enduro, the problem is still there, and the number of "In progress" transfers never reach capacity.

**Comment by scollazo** [comment]
For context, this is happening in a client that use  8 concurrent transfers and 8 MCP Clients in a server with 16 CPU's and 32 gb of ram, so not easy to reproduce...

**Comment by sevein** [comment]
> If you try to cancel the job, it goes into "Error", but no transfers in "Queue" state go into "In progress", so the transfer slot is unused.

With #292, the workflow should be able to release a slot during cancellation.
