### ISSUE TITLE
Problem: transfer/ingest polling activities retry indefinitely on 400 errors

### ISSUE THREAD

**Issue by sevein** [artefactual-labs/enduro#282]
It's been reported that Archivematica's [Transfer status] and [Ingest status] APIs may return a 400 error under conditions that are still being investigated. We could argue that it should return a 5xx error instead, but this is what we have to expect in Archivematica v1.13 or older.

In the transfer and ingest polling activities, 4xx and 5xx errors are considered retryable and the policy is to retry indefinitely with a constant back-off delay of five seconds. The immediate effect of this decision is that these workflows won't release the pipeline lock and may block processing until the situation is solved in the Archivematica pipeline.
It may be preferably to give up on recurrent errors after a while (10 minutes) - uses can always rely on the reporting capabilities to identify failed packages and retry them at some other point.

[Transfer status]: https://www.archivematica.org/en/docs/archivematica-1.13/dev-manual/api/api-reference-archivematica/#status
[Ingest status]: https://www.archivematica.org/en/docs/archivematica-1.13/dev-manual/api/api-reference-archivematica/#id1

**Comment by joel-simpson** [comment]
I agree that 10 minutes feels like a good time to give up on recurring errors... you've probably considered this already but  perhaps this should be a configurable value? 

I'm also not clear if, after failing a workflow, Enduro will actually release the pipeline block or whether that is a separate issue. If it doesn't then this change still has value -- it will reduce a huge amount of noise in logs etc and also reduce (admittedly not huge) compute power being used.

**Comment by sevein** [comment]
Yes, I'll make it configurable. Thanks for the reminder. I'm pretty sure the slot will be released when the polling activity fails but I'll double check.
