### ISSUE TITLE
Problem: Non NHA naming conventions fail transfer

### ISSUE THREAD

**Issue by jorikvankemenade** [artefactual-labs/enduro#32]
The problem of #9 has resurfaced in a new form. In 4d5fe1e53c5da576d92ba445b1fd8ca6594dd693 some additional NHA identifiers were introduced. The [nha parser](https://github.com/artefactual-labs/enduro/blob/4d5fe1e53c5da576d92ba445b1fd8ca6594dd693/internal/nha/parse.go) parses the filenames of uploads to Enduro. If the parsing fails the workflow fails with a non-retryable error.

I get that from the perspective of the NHA you want to fail if the naming convention is wrong, but from the perspective of a "general" tool, this is rather unfortunate. Do you already have any plans on how you want to approach this, and if so can I help in the implementation effort. Today's update to 19.2 broke my experimental environment.

I think the simplest solution at this point would be to introduce a basic parser. This parser will just strip the extension from the filename and that's it. You can switch between both parsers using a configuration flag. In a later stage, it might be worthwhile to introduce a way of configuring "custom" parsers, but I would say that it is not worth the time at this point.

Do you agree? If so I'll create a PR tomorrow. If not please let me know what you propose and if I can help.

**Comment by sevein** [comment]
@jorikvankemenade hopefully v0.19.3 will fix the issue that you're describing.

> I think the simplest solution at this point would be to introduce a basic parser. This parser will just strip the extension from the filename and that's it. You can switch between both parsers using a configuration flag. In a later stage, it might be worthwhile to introduce a way of configuring "custom" parsers, but I would say that it is not worth the time at this point.

That sounds like a good idea. Let's do it as part of a new issue if you're still interested. A config flag could work and that's kind of what I'm doing now with hooks, but I think we need to explore better ways to customize our workflow. Someone started an [implementation](https://github.com/checkr/states-language-cadence) of the Amazon States Language in Cadence, it's still early but I'm wondering if we could use it to allow users to implement [child workflows](https://cadenceworkflow.io/docs/07_goclient/05_child_workflows) using definitions provided by the users. Maxim share some extra thoughts about child workflows [here](https://stackoverflow.com/a/55840459), it seems to fit well. Also we could explore ways to inject activities provided by the users, e.g. via RPC plugins, etc...

**Comment by jorikvankemenade** [comment]
@sevein you are describing some options of the direction I am thinking of. I'll have to focus on some other problems first, but after that, this might definitely be a direction I would like to explore further.
