### ISSUE TITLE
Problem: transfers are abandoned if the workflow is interrupted

### ISSUE THREAD

**Issue by scollazo** [artefactual-labs/enduro#36]
There is no way to stop enduro without leaving transfers in an unknown state.

There should be a way to stop enduro gracefully, allowing all in progress tasks to finish without starting new ones.

**Comment by sevein** [comment]
Thanks @scollazo. Part of our workflow runs within a [session](https://cadenceworkflow.io/docs/07_goclient/15_sessions) (download, bundle, transfer, poll transfer, poll ingest and receipt delivery). Cadence detects that the worker running the session dies and terminates the session.

I think that we have to do a couple of things:
* Retry the session when `workflow.ErrSessionFailed` is received,
* Reduce the session window as much as possible (it spans over multiple activities, including poll-transfer and poll-ingest).

I've also filed #37 to describe the lack of the ability to deploy workers separately.

**Comment by scollazo** [comment]
While workers seems like a nice thing to have, I don't see how they'll solve the problem. Are you thinking about running a worker for each pipeline, and stop it in case of need?

**Comment by scollazo** [comment]
For the record, this cadence issue might be of interest https://github.com/uber-go/cadence-client/issues/775

**Comment by sevein** [comment]
Tentatife fix in 486be45bdb3e1c011f50e3abc60c255c6f238eb4.

**Comment by sevein** [comment]
Reminder: the semaphore that protects pipeline is still local and it's flushed when you kill Enduro so expect more transfer to enter the critical section. That's not something that we can control well until we solve #43.
