### ISSUE TITLE
Problem: bundle-activity fails for large transfers

### ISSUE THREAD

**Issue by jorikvankemenade** [artefactual-labs/enduro#41]
**Expected behaviour**
When you copy a large file or tar to a watched location Enduro creates a transfer. 

**Current behaviour**
When copying a large file the `bundle activity` will fail. Two examples:

![image](https://user-images.githubusercontent.com/7934339/73369336-be261480-42b2-11ea-8855-9b3372996123.png)

![image](https://user-images.githubusercontent.com/7934339/73369385-d302a800-42b2-11ea-9d87-8fd193bf5cc1.png)

This is caused by the way the filesystem events are handled by Enduro. A new workflow is triggered by a `Create` event ([code snippet](https://github.com/artefactual-labs/enduro/blob/9fe22a786fa41974cba08b0570c3742c07ab6657/internal/watcher/filesystem.go#L75)). This means that as soon as a new file is created, a new workflow is kicked off. 

For small files this works fine, for larger files, this introduces a problem. When looking at the full `fsnotify` stream of a file copy you will see that it consists fo a `Create` and *at least* one `Write` event. For example if I create a text file with a single line of text:

```
EVENT! fsnotify.Event{Name:"/home/jorik/Documents/pollingtest/test.txt", Op:Create}
EVENT! fsnotify.Event{Name:"/home/jorik/Documents/pollingtest/test.txt", Op:Write}
```

However, if I create a larger text file. For example one with the numbers 1 to 10000 (one per line):

```
EVENT! fsnotify.Event{Name:"/home/jorik/Documents/pollingtest/test.txt", Op:Create}
EVENT! fsnotify.Event{Name:"/home/jorik/Documents/pollingtest/test.txt", Op:Write}
EVENT! fsnotify.Event{Name:"/home/jorik/Documents/pollingtest/test.txt", Op:Write}
EVENT! fsnotify.Event{Name:"/home/jorik/Documents/pollingtest/test.txt", Op:Write}
EVENT! fsnotify.Event{Name:"/home/jorik/Documents/pollingtest/test.txt", Op:Write}
EVENT! fsnotify.Event{Name:"/home/jorik/Documents/pollingtest/test.txt", Op:Write}
EVENT! fsnotify.Event{Name:"/home/jorik/Documents/pollingtest/test.txt", Op:Write}
```

The file is created and incrementally written. However, the workflow is started as soon as the `Create` is captured. This means that we have a race condition between the filesystem copy and the `download-activity`. When the file copy is done *before* the `download-activity` task fires we are safe, in any other case the `download-activity` will download an incomplete file and the `bundle-activity` will fail. 

**Proposed solution**
Instead of triggering on the `Create` event, we must "know" when the file is fully copied. Unfortunately, I haven't thought of a completely resilient way as of yet. What we can do in the meantime is trigger some sort of watch for `Write` events on a newly created file. When there have been no `Write` events for some time (probably a few seconds, to accommodate network latency) , the workflow can be safely started.

**Comment by sevein** [comment]
So if the event is triggered before you're done writing the file, why don't you write the file somewhere else (within the same filesystem) and then move it?

**Comment by jorikvankemenade** [comment]
You mean a `cp` to a location outside the "watched directory" and then a `mv`? This works because a filesystem move is atomic. It would make a less user-friendly interface to the user IMHO, you have to "destroy" your original. But implementation wise it is indeed simpler.

**Comment by sevein** [comment]
The wait-after-write strategy seems too complicated, e.g. say the writer has to wait because the source becomes temporarily unavailable, how would you deal with that? There's also CLOSE_WRITE, but I don't think it's supported in fsnotify (see https://git.io/JvYjM). It turns out to be a hard problem. And it's not supported in all platforms I believe. I read this thing [article](https://lwn.net/Articles/789600/) recently that makes me question the atomicity of rename - it seems to ultimately depend on the filesystem that you're using?

**Comment by jorikvankemenade** [comment]
> The wait-after-write strategy seems too complicated (...)

I agree, the best it can do is make the whole thing less prone to error. At the cost of adding iffy moving parts.

> It turns out to be a hard problem.

Unfortunately, I have to agree. This is the main reason I opened an issue instead of a PR.

> it seems to ultimately depend on the filesystem that you're using

I believe you are right. I have another [source here](https://unix.stackexchange.com/questions/322038/is-mv-atomic-on-my-fs). The advantage of using a rename instead of a copy is that it is (generally) faster. So the race condition is *less likely* to show up. But as with the `wait-after-write` strategy, it is not failure-proof.

**Comment by sevein** [comment]
Marked as `wontfix`, but leaving the issue open until we can document this limitation in filesystem watchers and potential workarounds.

**Comment by sevein** [comment]
https://enduroproject.netlify.app/docs/user-manual/configuration/#ignore-string describes our solution to this problem.
