### ISSUE TITLE
Problem: download-activity has no reasonable timeout

### ISSUE THREAD

**Issue by jorikvankemenade** [artefactual-labs/enduro#50]
When running transfers for large videofiles (think 40+GB) I run into timeouts. The main problem is that the timeout seems to be missing context, or I am interpreting the workflow execution wrong.

The failure for `38` has an empty details field, although it seems to be related to the `36 DecisionTaskCompleted` in which is related to the `32 DecisionTaksScheduled`. However, I cannot find what this task should be and if indeed the 10-second timeout is hit. Do you have any idea what the problem can be, or how I can get more information from cadence or the logs? Thanks!

```
   1  WorkflowExecutionStarted     {WorkflowType:{Name:processing-workflow}, TaskList:{Name:global},
                                   Input:[{"CollectionID":0,"Event":{"WatcherName":"file-drop-dev","PipelineName":"archivematica-dev","RetentionPeriod":0,"StripT
                                   opLevelDir":false,"Key":"pm_D1V1_2201522-1.mkv"}}], ExecutionStartToCloseTimeoutSeconds:604800,
                                   TaskStartToCloseTimeoutSeconds:10, ContinuedFailureDetails:[], LastCompletionResult:[],
                                   OriginalExecutionRunId:8512d5b8-b28d-43b4-8d8b-0e87c3aa26ac, Identity:20451@archivematica-enduro-dev.cern.ch@,
                                   FirstExecutionRunId:8512d5b8-b28d-43b4-8d8b-0e87c3aa26ac, Attempt:0, FirstDecisionTaskBackoffSeconds:0, Header:{Fields:map{}}}
   2  DecisionTaskScheduled        {TaskList:{Name:global},
                                   StartToCloseTimeoutSeconds:10,
                                   Attempt:0}
   3  DecisionTaskStarted          {ScheduledEventId:2,
                                   Identity:20451@archivematica-enduro-dev.cern.ch@global,
                                   RequestId:febab472-6c5e-4b5b-ac07-76d3a02650be}
   4  DecisionTaskCompleted        {ExecutionContext:[],
                                   ScheduledEventId:2, StartedEventId:3,
                                   Identity:20451@archivematica-enduro-dev.cern.ch@global,
                                   BinaryChecksum:ff3a7e2391c2d9436744dba2fc563bf0}
   5  MarkerRecorded               {MarkerName:LocalActivity,
                                   Details:[{"activityId":"0","activityType":"createPackageLocalActivity","resultJson":"210\n","replayTime":"2020-02-03T19:16:23.14
                                   3058109+01:00"}], DecisionTaskCompletedEventId:4}
   6  MarkerRecorded               {MarkerName:LocalActivity,
                                   Details:[{"activityId":"1","activityType":"ParseNameLocalActivity","errReason":"cadenceInternal:Generic","errJson":"error
                                   parsing name: no matches","replayTime":"2020-02-03T19:16:23.1437395+01:00"}], DecisionTaskCompletedEventId:4}
   7  MarkerRecorded               {MarkerName:LocalActivity,
                                   Details:[{"activityId":"2","activityType":"loadConfigLocalActivity","resultJson":"{\"TempFile\":\"\",\"TransferID\":\"\",\"SIPID
                                   \":\"\",\"CollectionID\":210,\"Event\":{\"WatcherName\":\"file-drop-dev\",\"PipelineName\":\"archivematica-dev\",\"Reten tionPeriod
                                   ... .cern.ch\",\"Capacity\":4},\"PipelineID\":\"\",\"Hooks\":{\"hari\":{\"disabled\":true},\"prod\":{\"disabled\":true}},\"B
                                   undle\":{\"RelPath\":\"\",\"FullPath\":\"\",\"FullPathBeforeStrip\":\"\"}}\n","replayTime":"2020-02-03T19:16:23.14443499 7+01:00"}],
                                   DecisionTaskCompletedEventId:4}
   8  MarkerRecorded               {MarkerName:SideEffect, Details:[3
                                   "IjRkNWI0ZmNiLTdhYjMtNDQyOS05NDNiLTMwODdhNWNmMTBmMCIK"],
                                   DecisionTaskCompletedEventId:4}
   9  ActivityTaskScheduled        {ActivityId:4,
                                   ActivityType:{Name:internalSessionCreationActivity},
                                   TaskList:{Name:global__internal_session_creation},
                                   Input:["4d5b4fcb-7ab3-4429-943b-3087a5cf10f0"],
                                   ScheduleToCloseTimeoutSeconds:604800,
                                   ScheduleToStartTimeoutSeconds:600,
                                   StartToCloseTimeoutSeconds:604800,
                                   HeartbeatTimeoutSeconds:10,
                                   DecisionTaskCompletedEventId:4,
                                   RetryPolicy:{InitialIntervalInSeconds:1,
                                   BackoffCoefficient:1.1, MaximumIntervalInSeconds:10,
                                   MaximumAttempts:0, NonRetriableErrorReasons:[len=4],
                                   ExpirationIntervalInSeconds:600},
                                   Header:{Fields:map{}}}
  10  WorkflowExecutionSignaled    {SignalName:4d5b4fcb-7ab3-4429-943b-3087a5cf10f0,
                                   Input:[{"Tasklist":"dac0b13b-4584-4ba2-8956-5b8ebf538e2e@archivematica-enduro-dev.cern.ch","HostName":"archivematica-enduro-de
                                   v.cern.ch","ResourceID":"dac0b13b-4584-4ba2-8956-5b8ebf538e2e"}], Identity:20451@archivematica-enduro-dev.cern.ch@}
  11  DecisionTaskScheduled        {TaskList:{Name:archivematica-enduro-dev.cern.ch:754640ce-2c14-4ba4-8193-f1b5fa5bfbc9},
                                   StartToCloseTimeoutSeconds:10, Attempt:0}
  12  DecisionTaskStarted          {ScheduledEventId:11,
                                   Identity:20451@archivematica-enduro-dev.cern.ch@global,
                                   RequestId:c53a7a48-9639-4064-bb6a-14d6339c7bf7}
  13  DecisionTaskCompleted        {ExecutionContext:[],
                                   ScheduledEventId:11, StartedEventId:12,
                                   Identity:20451@archivematica-enduro-dev.cern.ch@global,
                                   BinaryChecksum:ff3a7e2391c2d9436744dba2fc563bf0}

  14  ActivityTaskScheduled        {ActivityId:5, ActivityType:{Name:acquire-pipeline-activity},
                                   TaskList:{Name:dac0b13b-4584-4ba2-8956-5b8ebf538e2e@archivematica-enduro-dev.cern.ch},
                                   Input:["archivematica-dev"], ScheduleToCloseTimeoutSeconds:315360000,
                                   ScheduleToStartTimeoutSeconds:315360000, StartToCloseTimeoutSeconds:5,
                                   HeartbeatTimeoutSeconds:0, DecisionTaskCompletedEventId:13,
                                   RetryPolicy:{InitialIntervalInSeconds:2, BackoffCoefficient:1,
                                   MaximumIntervalInSeconds:2, MaximumAttempts:0, NonRetriableErrorReasons:[len=0],
                                   ExpirationIntervalInSeconds:315360000}, Header:{Fields:map{}}}
  15  ActivityTaskStarted          {ScheduledEventId:14,
                                   Identity:20451@archivematica-enduro-dev.cern.ch@global,
                                   RequestId:372625bf-738a-4082-9121-31b191140af2,
                                   Attempt:0}
  16  ActivityTaskCompleted        {Result:[], ScheduledEventId:14, StartedEventId:15,
                                   Identity:20451@archivematica-enduro-dev.cern.ch@global}
  17  DecisionTaskScheduled        {TaskList:{Name:archivematica-enduro-dev.cern.ch:754640ce-2c14-4ba4-8193-f1b5fa5bfbc9},
                                   StartToCloseTimeoutSeconds:10, Attempt:0}
  18  DecisionTaskStarted          {ScheduledEventId:17,
                                   Identity:20451@archivematica-enduro-dev.cern.ch@global,
                                   RequestId:c0523288-809a-478d-802d-dbb2f6769805}
  19  DecisionTaskCompleted        {ExecutionContext:[],
                                   ScheduledEventId:17, StartedEventId:18,
                                   Identity:20451@archivematica-enduro-dev.cern.ch@global,
                                   BinaryChecksum:ff3a7e2391c2d9436744dba2fc563bf0}
  20  MarkerRecorded               {MarkerName:LocalActivity,
                                   Details:[{"activityId":"6","activityType":"setStatusInProgressLocalActivity","replayTime":"2020-02-03T19:16:23.328016092+01:00"}
                                   ], DecisionTaskCompletedEventId:19}
  21  ActivityTaskScheduled        {ActivityId:7, ActivityType:{Name:download-activity},
                                   TaskList:{Name:dac0b13b-4584-4ba2-8956-5b8ebf538e2e@archivematica-enduro-dev.cern.ch},
                                   Input:[{"WatcherName":"file-drop-dev","PipelineName":"archivematica-dev","RetentionPeriod":0,"StripTopLevelDir":false,"Key":"p
                                   m_D1V1_2201522-1.mkv"}], ScheduleToCloseTimeoutSeconds:604800, ScheduleToStartTimeoutSeconds:604800,
                                   StartToCloseTimeoutSeconds:600, HeartbeatTimeoutSeconds:0, DecisionTaskCompletedEventId:19,
                                   RetryPolicy:{InitialIntervalInSeconds:1, BackoffCoefficient:2, MaximumIntervalInSeconds:600, MaximumAttempts:5,
                                   NonRetriableErrorReasons:[len=1], ExpirationIntervalInSeconds:600}, Header:{Fields:map{}}}
  22  ActivityTaskStarted          {ScheduledEventId:21,
                                   Identity:20451@archivematica-enduro-dev.cern.ch@global,
                                   RequestId:6944fa55-7186-4022-98a6-9318873c9765,
                                   Attempt:4}
  23  ActivityTaskTimedOut         {Details:[],
                                   ScheduledEventId:21,
                                   StartedEventId:22,
                                   TimeoutType:START_TO_CLOSE}
  24  DecisionTaskScheduled        {TaskList:{Name:archivematica-enduro-dev.cern.ch:754640ce-2c14-4ba4-8193-f1b5fa5bfbc9},
                                   StartToCloseTimeoutSeconds:10, Attempt:0}
  25  DecisionTaskStarted          {ScheduledEventId:24,
                                   Identity:20451@archivematica-enduro-dev.cern.ch@global,
                                   RequestId:83c24c57-25b1-446c-945f-c9ef56b2769c}
  26  DecisionTaskCompleted        {ExecutionContext:[],
                                   ScheduledEventId:24, StartedEventId:25,
                                   Identity:20451@archivematica-enduro-dev.cern.ch@global,
                                   BinaryChecksum:ff3a7e2391c2d9436744dba2fc563bf0}
  27  MarkerRecorded               {MarkerName:LocalActivity,
                                   Details:[{"activityId":"8","activityType":"releasePipelineLocalActivity","replayTime":"2020-02-03T20:06:38.236382208+01:00"}],
                                   DecisionTaskCompletedEventId:26}
  28  ActivityTaskCancelRequested  {ActivityId:4,
                                   DecisionTaskCompletedEventId:26}
  29  ActivityTaskScheduled        {ActivityId:9, ActivityType:{Name:internalSessionCompletionActivity},
                                   TaskList:{Name:dac0b13b-4584-4ba2-8956-5b8ebf538e2e@archivematica-enduro-dev.cern.ch},
                                   Input:["4d5b4fcb-7ab3-4429-943b-3087a5cf10f0"], ScheduleToCloseTimeoutSeconds:6,
                                   ScheduleToStartTimeoutSeconds:3, StartToCloseTimeoutSeconds:3,
                                   HeartbeatTimeoutSeconds:0, DecisionTaskCompletedEventId:26, Header:{Fields:map{}}}
  30  ActivityTaskStarted          {ScheduledEventId:29,
                                   Identity:20451@archivematica-enduro-dev.cern.ch@global,
                                   RequestId:109cad86-6b38-4f4d-88f9-e68881148320,
                                   Attempt:0}
  31  ActivityTaskCompleted        {Result:[], ScheduledEventId:29, StartedEventId:30,
                                   Identity:20451@archivematica-enduro-dev.cern.ch@global}
  32  DecisionTaskScheduled        {TaskList:{Name:archivematica-enduro-dev.cern.ch:754640ce-2c14-4ba4-8193-f1b5fa5bfbc9},
                                   StartToCloseTimeoutSeconds:10, Attempt:0}
  33  ActivityTaskStarted          {ScheduledEventId:9,
                                   Identity:20451@archivematica-enduro-dev.cern.ch@global,
                                   RequestId:37418cd6-508c-4c47-82af-e1dc165670ba,
                                   Attempt:0}
  34  ActivityTaskCompleted        {Result:[], ScheduledEventId:9, StartedEventId:33,
                                   Identity:20451@archivematica-enduro-dev.cern.ch@global}
  35  DecisionTaskStarted          {ScheduledEventId:32,
                                   Identity:20451@archivematica-enduro-dev.cern.ch@global,
                                   RequestId:abcd49af-2b06-4cf5-921a-ad55a252f3ca}
  36  DecisionTaskCompleted        {ExecutionContext:[],
                                   ScheduledEventId:32, StartedEventId:35,
                                   Identity:20451@archivematica-enduro-dev.cern.ch@global,
                                   BinaryChecksum:ff3a7e2391c2d9436744dba2fc563bf0}
  37  MarkerRecorded               {MarkerName:LocalActivity,
                                   Details:[{"activityId":"10","activityType":"updatePackageLocalActivity","replayTime":"2020-02-03T20:06:38.341754446+01:00"}],
                                   DecisionTaskCompletedEventId:36}
  38  WorkflowExecutionFailed      {Reason:cadenceInternal:Timeout
                                   START_TO_CLOSE,
                                   Details:[],
                                   DecisionTaskCompletedEventId:36}
```

**Comment by sevein** [comment]
I think that the anomaly happened back in event#21 (download-activity). The activity exceeded the timeout (10 minutes). A total of five attempts were made, as per in the attached retry policy. But once the retries are maxed out, the activity returns an error and the workflow just gives up. We may want to introduce some additional error management at that point (see #38 for more).
The following events that the history reads relate to the graceful exit process programmed in the workflow, which include ending the worker session and doing some application state clean-ups.

The activity options are:

```go
workflow.ActivityOptions{
	ScheduleToStartTimeout: forever,
	StartToCloseTimeout:    time.Minute * 10,
	RetryPolicy: &cadence.RetryPolicy{
		InitialInterval:          time.Second,
		BackoffCoefficient:       2,
		MaximumInterval:          time.Minute * 10,
		ExpirationInterval:       time.Minute * 10,
		MaximumAttempts:          5,
		NonRetriableErrorReasons: []string{wferrors.NRE},
	},
}
```

A good start would be to make `StartToCloseTimeout` much higher. I don't know what would be a reasonable timeout, `time.Hour * 2` maybe?

Eventually I think that you'd want "download-activity" to be implemented as a heartbeating activity such "poll-transfer" or "poll-ingest", but it's trickier. Heartbeating activities have some good advantages:
* You don't have to guess what's a good value for StartToCloseTimeout because the activity can continue execution as long as it's also able to transmit heartbeats to the workflow manager. But you may also want to have some logic to interrupt the process if the download is stalled for a long time.
* They can communicate progress as part of the hearbeat payload (e.g. bytes downloaded, download speed, progress meter...).
* They also receive cancelation signals, so an activity can be implemented to interrupt the download gracefully, remove temporary files, etc...

**Comment by jorikvankemenade** [comment]
> A good start would be to make `StartToCloseTimeout` much higher. I don't know what would be a reasonable timeout, `time.Hour * 2` maybe?

Yes, this seems to be the problem. I was a bit thrown off by the timing out and retry behaviour for cadence. When the download times out because of hitting the `StartToCloseTimeout` limit, it is retried. As a result, I had what seemed to be really long-running downloads, but where actually retried downloads. 

So I think it would be a good idea to list the `cadenceInternal:Timeout TIMEOUT_TYPE` as one of the `NonRetriableErrorReasons`. This way we won't retry an activity that just takes to long for whatever reason. 

> Eventually I think that you'd want "download-activity" to be implemented as a heartbeating activity such "poll-transfer" or "poll-ingest".

Solid reasoning, I agree that this makes more sense. It is near impossible to set a reasonable default here. For small files, 30 minutes is just pointless. For really big transfers 1 hour might not be enough.
For now, increasing the timeout works.

**Comment by sevein** [comment]
> So I think it would be a good idea to list the cadenceInternal:Timeout TIMEOUT_TYPE as one of the NonRetriableErrorReasons.

Cadence server will stop when cadenceInternla:Timeout is returned which happens when the retries have already happened. In [RetryPolicy](https://godoc.org/go.uber.org/cadence/internal#RetryPolicy):

    // Non-Retriable errors. This is optional. Cadence server will stop retry if error reason matches this list.
    // Error reason for custom error is specified when your activity/workflow return cadence.NewCustomError(reason).
    // Error reason for panic error is "cadenceInternal:Panic".
    // Error reason for any other error is "cadenceInternal:Generic".
    // Error reason for timeouts is: "cadenceInternal:Timeout TIMEOUT_TYPE". TIMEOUT_TYPE could be START_TO_CLOSE or HEARTBEAT.
    // Note, cancellation is not a failure, so it won't be retried.
    NonRetriableErrorReasons []string

One approach would be to unwrap the error returned by a.manager.Watcher.Download and try to decide where exactly you'd want to return non-retryable error. E.g. a `PermissionDenied` is something where we wouldn't have to retry. Remember that we're using gocloud.dev to download the objects and that it implements custom error codes (https://godoc.org/gocloud.dev/gcerrors). They've done a huge amount of work to wrap erros from different cloud APIs consistently, including filesystems.

```go
if err := a.manager.Watcher.Download(ctx, file, event); err != nil {
    return "", wferrors.NonRetryableError(fmt.Errorf("error downloading blob: %v", err))
}
```

> What do you think about changing the title of the issue to something like: "Problem: download-activity has no reasonable timeout". This reflects the actual problem better, and the issue already contains a potential solution.

Sounds great!

**Comment by jorikvankemenade** [comment]
> Cadence server will stop when cadenceInternla:Timeout is returned which happens when the retries have already happened. In RetryPolicy:

I guess I misinterpreted that line on the `RetryPolicy`. I thought the list was giving some examples you could add to the list. Like for example `cadenceInternal:Timeout` as I suggested. Are you sure my interpretation is wrong? I am pretty sure that my downloads took way longer than 10 minutes before failing with a timeout. I think the ~ 1-hour mark would be closer. This would correspond to 6 retries of a 10-minute timeout, which is the setting. I'll run a test to verify this.

**Comment by jorikvankemenade** [comment]
I just set the `ActivityOpts` to:

```go
	return workflow.WithActivityOptions(ctx, workflow.ActivityOptions{
		ScheduleToStartTimeout: forever,
		StartToCloseTimeout:    time.Minute * 2,
		RetryPolicy: &cadence.RetryPolicy{
			InitialInterval:    time.Second,
			BackoffCoefficient: 2,
			MaximumInterval:    time.Minute * 10,
			ExpirationInterval: time.Minute * 10,
			MaximumAttempts:    5,
			NonRetriableErrorReasons: []string{wferrors.NRE, "cadenceInternal:Timeout START_TO_CLOSE"},
			//NonRetriableErrorReasons: []string{wferrors.NRE},
		},
```
This caused my workflow to fail after 2 minutes. When I used the previous version of the `NonRetriableErrorReasons`, the workflow only failed after 10 minutes. So I think we might want to take this into cosideration when looking at failure and retry behaviour.

**Comment by sevein** [comment]
Ok, I think that your interpretation of RetryPolicy is correct. It's a really good point too, IIRC your'e saying that we shouldn't bother to retry an activity that failed only because it was too slow. It makes me want to revisit all the retry policies I've used!

My next question would be what would you do in the workflow when download-activity returns the `TimeoutType: START_TO_CLOSE` error?

The approach I'm working on in hari/prod activities is to use [async completion](https://cadenceworkflow.io/docs/07_goclient/12_activity_async_completion) to present the user with some different options to move forward, e.g. "retry again", "abandon"... I'm also introducing two new collection statuses: "pending" (awaiting user decision) and "abandoned" (user decided to give up) - see https://gist.github.com/sevein/dd36c2af23fd0d9e2e2438d8eb091314 for more. It kind of complicates the workflow code but we think it's necessary.

**Comment by jorikvankemenade** [comment]
> It's a really good point too, IIUC you're saying that we shouldn't bother to retry an activity that failed only because it was too slow.

Yes, I think we really need to think about when retrying makes sense and when it doesn't. Like you said earlier, an authorization error will not be resolved if you try 10 more times. However, if a service is unavailable it might make sense to retry for a bit because it might come up again.

So the real question here would be: what is the meaning of the `StartToCloseTimeout`. I would see this as a last resort. If all error management fails, and a task is stuck for whatever unknown reason we want to fail to a safe state. A reasonable value for this would be any situation where it is impossible for us to distinguish a really slow system, a broken system, or a "bad workload". If we consider our download example. when downloading a transfer takes more than 2 hours (just an arbitrarily large value)  you could argue that we have reached this situation. Because we either:
1. Download at such a slow speed that we likely have a network problem.
2. The job is stuck doing nothing for an unknown reason.
3. Everything is working as intended, so we must have an extremely large transfer. This will likely cause problems down the line in Archivematica anyways - so better fail now than after 24+ hours.

So I think that for every activity we should make some conscious decisions about the retry and failure behaviour. 
1. When do we want to retry, i.e. 50x or 420 status codes. 
2. When do we give up, i.e. if this step takes longer than 2 hours it is unreasonable. 
3. When do we know that we have a failure, i.e. almost all 4xx status codes. 

What to do in this case is the next question.

> The approach I'm working on in hari/prod activities is to use async completion to present the user with some different options to move forward, e.g. "retry again", "abandon"... 

I welcome this very much. I have already had Enduro transfers fail on me because not all possible workflow paths are configurable via the Processing configuration. If I get a warning and can go to the Archivematica or Enduro dashboard to resolve the issue, without the workflow failing, would be perfect. 

But it could also help to recover from outages. For example, we use network storage for all of our material. If that storage is down we cannot download the artifacts. When the storage is back up it would be perfectly reasonable to resume at the beginning of the download step. This way Enduro could assist us in recovering from the failure, it acts as a todo list of transfers that have failed due to the outage. If we resolved all issues we know we resolved the issues from the outage.

**Comment by sevein** [comment]
Well put! I realise that this fine-grained control we have now around error management also comes with great responsibilities! I've already done some of what you're describing in a few critical places, but there's more work to do. Archivematica is also peculiar in that it gets overwhelmed pretty easily and its API isn't particularly well-rounded. If you look at pipeline/status.go, there're some tuning still needed but I'm already paying attention to deadlines, status codes (needs polishing), etc...

> I welcome this very much. I have already had Enduro transfers fail on me because not all possible workflow paths are configurable via the Processing configuration. If I get a warning and can go to the Archivematica or Enduro dashboard to resolve the issue, without the workflow failing, would be perfect.

Cool. I'm currently focused on receipt delivery but the solution could be later extended to other sections of the workflow.

**Comment by sevein** [comment]
Would the following activity options work for you? I can make this change pretty quickly.

```go
workflow.ActivityOptions{
		ScheduleToStartTimeout: forever,
		StartToCloseTimeout:    time.Hour * 2,
		RetryPolicy: &cadence.RetryPolicy{
			InitialInterval:    time.Second,
			BackoffCoefficient: 2,
			MaximumInterval:    time.Minute * 10,
			ExpirationInterval: time.Minute * 10,
			MaximumAttempts:    5,
			NonRetriableErrorReasons: []string{
				wferrors.NRE,
				"cadenceInternal:Timeout START_TO_CLOSE",
			},
		},
	}
```

**Comment by jorikvankemenade** [comment]
Yes, I have exactly this on my own fork,
