### ISSUE TITLE
Problem: when acquire-pipeline-activity in progress, collection status is queued

### ISSUE THREAD

**Issue by joel-simpson** [artefactual-labs/enduro#74]
Expected Behaviour: 

When an activity in an Enduro workflow is "in progress", the status of the collection should be "in progress".

Current behaviour: 

When the acquire-pipeline-activity in progress the collection status is "queued".  

This is a minor problem -- in the normal course of events, acquiring a pipeline is quick and the collection status will move on to "in progress" once the folllowing activity starts. Right now it is more of a problem because we are seeing an issue where acquire-pipeline-activity is failing. 

This first screenshot shows the collection status of QUEUED

![Screenshot from 2020-02-24 13-50-07](https://user-images.githubusercontent.com/17187309/75183176-f5e87680-570f-11ea-9b8f-0c10462bd60f.png)

This second screenshot shows that one of the QUEUED collections actually does have an activity in progress (and see how on the left the workflow shows a status of "Active"): 

![Screenshot from 2020-02-24 13-49-59](https://user-images.githubusercontent.com/17187309/75183237-1adce980-5710-11ea-9a84-e870e3a0ee0b.png)

**Comment by sevein** [comment]
I've managed to reproduce this locally where a new installation of Enduro reuses an existing Cadence domain with running workflows. We could find ways to avoid this but I think it's much simpler to assume that new domains are provisioned, or at least workflows in execution are terminated beforehand. I'll close this but feel free to reopen if it comes up again.
