### ISSUE TITLE
Problem: filesystem polling without inotify does not trigger a new transfer

### ISSUE THREAD

**Issue by jorikvankemenade** [artefactual-labs/enduro#8]
**Problem**
When using one of our own mounted filesystems Enduro will not catch changes in the filesystem when made from another node. I.e if I move a file into the watched directory on my Enduro VM a new transfer is triggered. If I do the same move from a different system, the new file is visible in my Enduro VM's filesystem but no change is triggered. 

I think this might have to do with inotify, I am not sure yet, but I am in the process of finding out. But in the meantime, I thought I would try filesystem polling instead. However, both on my local filesystem, as on network mounted storage the polling does not seem to work.

**How to reproduce**
Add the following filesystem watcher to the Enduro config:

```shell
[[watcher.filesystem]]
name = "file-drop"
path = "/home/archivematica/file-drop/"
inotify = false
pipeline = "am"
```

Then run the following:

```shell
~$ cp /some/file /home/archivematica/file-drop/
```

This will not trigger a new transfer. Change the config to `inotify = true` and a new transfer will be triggered.

**Comment by sevein** [comment]
Perhaps the poller in the filenotify package is only monitoring files? I thought I had tested it!

**Comment by jorikvankemenade** [comment]
Yes, I think this is the case.  If you look at the [watch function](https://github.com/moby/moby/blob/master/pkg/filenotify/poller.go#L147) you'll see that it uses `stat` to find if there has been a change. In the case of a directory, each change in the directory is pushed to the watcher as a write event:

```go
if fi.ModTime() != lastFi.ModTime() || fi.Size() != lastFi.Size() {
    if err := w.sendEvent(fsnotify.Event{Op: fsnotify.Write, Name: fi.Name()}, chClose); err != nil {
        return
    }
    lastFi = fi
    continue
}
```

Which in turn is ignored by the `FileWatcher` loop:

```go
case event, ok := <-w.fsw.Events():
    if !ok || event.Op != fsnotify.Create {
        continue
    }
    w.ch <- &event
```

So if you have the time it would be nice if you could verify my tests. But judging from the code it shouldn't work.

**Comment by jorikvankemenade** [comment]
I found a Go package that supports directory polling (https://github.com/radovskyb/watcher). I can run a few tests to see if it will work for Enduro, and if it does I can open a PR.

**Comment by sevein** [comment]
Thanks @jorikvankemenade. I did that exact same thing yesterday, a priority for me because our customer is going to be in the same situation as soon as they start testing with NFS. See d2606afbd43f9630bfe9d86d2b8ba60fce76ecb9. v0.5.0 is building as I speak.

**Comment by jorikvankemenade** [comment]
@sevein the fix works for us, thanks for notifying me!
